### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Minipada/superkolo#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

**Comment by Minipada** [comment]
Hi @unixorn I didn't expect this to be seen by anyone, I just added it

**Comment by unixorn** [comment]
I check every day or two for new ZSH content on GitHub to add to the list.

**Comment by unixorn** [comment]
Thanks, adding in https://github.com/unixorn/awesome-zsh-plugins/pull/671
